/**
 * Copyright (c) 2017-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import classnames from 'classnames';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import Translate from '@docusaurus/Translate';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import useBaseUrl from '@docusaurus/useBaseUrl';
import styles from './styles.module.css';

const features = [
  {
    title: <Translate id="frontpage.sec1.item1.title">Web 开发</Translate>,
    imageUrl: 'img/undraw_version_control.svg',
    description: (
      <Translate
        id="frontpage.sec1.item1"
        values={{
          link1: <a href="https://vuejs.org/">Vue</a>,
          link2: <a href="https://docusaurus.io">Docusaurus</a>,
        }}
      >
        {
          '在C社，学习 {link1}, {link2} 等多个前端框架，使用 GitHub 进行多人合作项目开发，并用所学的技巧创建自己的个人页面，参与社团平台搭建，充分展现你的创意与才智！'
        }
      </Translate>
    ),
  },
  {
    title: <Translate id="frontpage.sec1.item2.title">算法竞赛</Translate>,
    imageUrl: 'img/undraw_docusaurus_tree.svg',
    description: (
      <Translate id="frontpage.sec1.item2">
        在C社，与大佬交流竞赛经验与技巧，深入了解各类数据结构与算法，备赛NOIP，
        组队参加力扣周赛、洛谷月赛等算法竞赛，在磨练中提升自己的功力！
      </Translate>
    ),
  },
  {
    title: <Translate id="frontpage.sec1.item3.title">人工智能探索</Translate>,
    imageUrl: 'img/undraw_docusaurus_react.svg',
    description: (
      <Translate id="frontpage.sec1.item3">
        在C社，感受时代科技的前沿，探究人工智能与机器学习的奥秘，
        亲手设计一个自己的神经网络，并训练它做一切你能想象得到的疯狂的事！
      </Translate>
    ),
  },
];

function Home() {
  const context = useDocusaurusContext();
  const { siteConfig = {} } = context;
  return (
    <Layout
      title={`Hello from ${siteConfig.title}`}
      description="C社 << Computerization << 世外信息化社"
    >
      <header className={classnames('hero hero--primary', styles.heroBanner)}>
        <div className="container">
          <h1 className="hero__title">{siteConfig.title}</h1>
          <p className="hero__subtitle">{siteConfig.tagline}</p>
          <div className={styles.buttons}>
            <Link
              className={classnames(
                'button button--outline button--secondary button--lg',
                styles.getStarted
              )}
              id={styles.getStarted}
              to={useBaseUrl('docs/about-us')}
            >
              <Translate id="frontpage.button">了解更多</Translate>
            </Link>
          </div>
        </div>
      </header>
      <main>
        {features && features.length && (
          <section className={styles.features}>
            <div className="container">
              <div className="row">
                <div className="col text--center">
                  <h2>
                    <Translate id="frontpage.sec1">我们的活动</Translate>
                  </h2>
                </div>
              </div>
              <div className="row">
                {features.map(({ imageUrl, title, description }, idx) => (
                  <div
                    // This code is auto-generated by docusaurus
                    // Anyway we're going to implement our own index [age] some day later
                    // eslint-disable-next-line react/no-array-index-key
                    key={idx}
                    className={classnames('col col--4', styles.feature)}
                  >
                    {imageUrl && (
                      <div className="text--center">
                        <img
                          className={styles.featureImage}
                          src={useBaseUrl(imageUrl)}
                          alt={title}
                        />
                      </div>
                    )}
                    <h3>{title}</h3>
                    <p>{description}</p>
                  </div>
                ))}
              </div>
              <div className="row">
                <div className="col text--center">
                  <div className={classnames(styles.caption)}>
                    <Translate id="frontpage.sec1.imgsrc">图片来源：</Translate>
                    <a href="https://docusaurus.io/">
                      <Translate id="frontpage.sec1.imgsrc.link">
                        Docusaurus 官方文档
                      </Translate>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </section>
        )}
        <section className={styles.features}>
          <div className="container">
            <div className="row">
              <div className="col text--center">
                <h2>
                  <Translate id="frontpage.sec2.title">最新动态</Translate>
                </h2>
              </div>
            </div>
            <div className="row">
              <div className="col">
                <Translate id="frontpage.sec2.item1">
                  我们的主页正式上线了！
                </Translate>
              </div>
            </div>
          </div>
        </section>
      </main>
    </Layout>
  );
}

export default Home;
